 function AppendCharacter ( ChrToAppend ) 
 { 
   document.GET.keyword.value += ChrToAppend;
 } //end AppendCharacter 
 document.write('<table>'); 
 document.write('<tr>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0633" value=" \u0633 " onclick=AppendCharacter("\u0633")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0632" value=" \u0632 " onclick=AppendCharacter("\u0632")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0631" value=" \u0631 " onclick=AppendCharacter("\u0631")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0630" value=" \u0630 " onclick=AppendCharacter("\u0630")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u062f" value=" \u062f " onclick=AppendCharacter("\u062f")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u062e" value=" \u062e " onclick=AppendCharacter("\u062e")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u062d" value=" \u062d " onclick=AppendCharacter("\u062d")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u062c" value=" \u062c " onclick=AppendCharacter("\u062c")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u062b" value=" \u062b " onclick=AppendCharacter("\u062b")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u062a" value=" \u062a " onclick=AppendCharacter("\u062a")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0628" value=" \u0628 " onclick=AppendCharacter("\u0628")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0627" value=" \u0627 " onclick=AppendCharacter("\u0627")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0625" value=" \u0625 " onclick=AppendCharacter("\u0625")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0623" value=" \u0623 " onclick=AppendCharacter("\u0623")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 
  
 document.write('<TABLE>'); 
 document.write('<TR>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0646" value=" \u0646 " onclick=AppendCharacter("\u0646")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0645" value=" \u0645 " onclick=AppendCharacter("\u0645")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0644" value=" \u0644 " onclick=AppendCharacter("\u0644")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0643" value=" \u0643 " onclick=AppendCharacter("\u0643")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0642" value=" \u0642 " onclick=AppendCharacter("\u0642")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0641" value=" \u0641 " onclick=AppendCharacter("\u0641")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u063a" value=" \u063a " onclick=AppendCharacter("\u063a")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0639" value=" \u0639 " onclick=AppendCharacter("\u0639")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0638" value=" \u0638 " onclick=AppendCharacter("\u0638")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0637" value=" \u0637 " onclick=AppendCharacter("\u0637")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0636" value=" \u0636 " onclick=AppendCharacter("\u0636")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0635" value=" \u0635 " onclick=AppendCharacter("\u0635")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0634" value=" \u0634 " onclick=AppendCharacter("\u0634")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 
  
 document.write('<TABLE>'); 
 document.write('<TR>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u06b9" value=" \u06b9 " onclick=AppendCharacter("\u06b9")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u06a3" value=" \u06a3 " onclick=AppendCharacter("\u06a3")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u06a0" value=" \u06a0 " onclick=AppendCharacter("\u06a0")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u06fb" value=" \u06fb " onclick=AppendCharacter("\u06fb")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0694" value=" \u0694 " onclick=AppendCharacter("\u0694")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u068a" value=" \u068a " onclick=AppendCharacter("\u068a")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0686" value=" \u0686 " onclick=AppendCharacter("\u0686")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u06E9" value=" \u06E9 " onclick=AppendCharacter("\u06E9")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0621" value=" \u0621 " onclick=AppendCharacter("\u0621")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0629" value=" \u0629 " onclick=AppendCharacter("\u0629")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u064a" value=" \u064a " onclick=AppendCharacter("\u064a")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0649" value=" \u0649 " onclick=AppendCharacter("\u0649")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0648" value=" \u0648 " onclick=AppendCharacter("\u0648")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0647" value=" \u0647 " onclick=AppendCharacter("\u0647")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 
  
 document.write('<TABLE>'); 
 document.write('<TR>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0622" value=" \u0622 " onclick=AppendCharacter("\u0622")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0671" value=" \u0671 " onclick=AppendCharacter("\u0671")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0640" value=" \u0640 " onclick=AppendCharacter("\u0640")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0746" value=" \u0746 " onclick=AppendCharacter("\u0640\u200d\u070f\u0746")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0734" value=" \u0734 " onclick=AppendCharacter("\u0640\u200d\u070f\u0734")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0328" value=" \u0328 " onclick=AppendCharacter("\u0640\u0328")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u065c" value=" \u065c " onclick=AppendCharacter("\u065c")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0657" value=" \u0657 " onclick=AppendCharacter("\u0657")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0652" value=" \u0652 " onclick=AppendCharacter("\u0652")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0651" value=" \u0651 " onclick=AppendCharacter("\u0651")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u0650" value=" \u0650 " onclick=AppendCharacter("\u0650")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u064f" value=" \u064f " onclick=AppendCharacter("\u064f")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u064e" value=" \u064e " onclick=AppendCharacter("\u064e")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u064d" value=" \u064d " onclick=AppendCharacter("\u064d")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u064c" value=" \u064c " onclick=AppendCharacter("\u064c")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 30; font-weight:bold" name="\u064b" value=" \u064b " onclick=AppendCharacter("\u064b")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 

 document.write('<TABLE>'); 
 document.write('<TR>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u066C" value=" \u066C " onclick=AppendCharacter("\u066C")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u066B" value=" \u066B " onclick=AppendCharacter("\u066B")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u061F" value=" \u061F " onclick=AppendCharacter("\u061F")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u061B" value=" \u061B " onclick=AppendCharacter("\u061B")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0669" value=" \u0669 " onclick=AppendCharacter("\u0669")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0668" value=" \u0668 " onclick=AppendCharacter("\u0668")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0667" value=" \u0667 " onclick=AppendCharacter("\u0667")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0666" value=" \u0666 " onclick=AppendCharacter("\u0666")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0665" value=" \u0665 " onclick=AppendCharacter("\u0665")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0664" value=" \u0664 " onclick=AppendCharacter("\u0664")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0663" value=" \u0663 " onclick=AppendCharacter("\u0663")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0669" value=" \u0662 " onclick=AppendCharacter("\u0662")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0661" value=" \u0661 " onclick=AppendCharacter("\u0661")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0660" value=" \u0660 " onclick=AppendCharacter("\u0660")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 
  
 document.write('<TABLE>'); 
 document.write('<TR>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" name="space" value=" Space " onclick=AppendCharacter("&#032;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" name="space" value=" Enter " onclick=AppendCharacter("\\n")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0656" value=" \u0656 " onclick=AppendCharacter("\u0656")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0655" value=" \u0655 " onclick=AppendCharacter("\u0655")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0654" value=" \u0654 " onclick=AppendCharacter("\u0654")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0670" value=" \u0670 " onclick=AppendCharacter("\u0670")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 17; font-weight:bold" name="\u0653" value=" \u0653 " onclick=AppendCharacter("\u0653")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 