 function AppendCharacter ( ChrToAppend ) 
 { 
   document.GET.keyword.value += ChrToAppend; 
 } //end AppendCharacter 
 document.write('<table>'); 
 document.write('<tr>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02949" value="&#02949;" onclick=AppendCharacter("&#02949;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02950" value="&#02950;" onclick=AppendCharacter("&#02950;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02951" value="&#02951;" onclick=AppendCharacter("&#02951;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02952" value="&#02952;" onclick=AppendCharacter("&#02952;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02953" value="&#02953;" onclick=AppendCharacter("&#02953;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02954" value="&#02954;" onclick=AppendCharacter("&#02954;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02958" value="&#02958;" onclick=AppendCharacter("&#02958;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02959" value="&#02959;" onclick=AppendCharacter("&#02959;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02960" value="&#02960;" onclick=AppendCharacter("&#02960;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02962" value="&#02962;" onclick=AppendCharacter("&#02962;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02963" value="&#02963;" onclick=AppendCharacter("&#02963;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02964" value="&#02964;" onclick=AppendCharacter("&#02964;")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 
  
 document.write('<TABLE>'); 
 document.write('<TR>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02965" value="&#02965;" onclick=AppendCharacter("&#02965;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02969" value="&#02969;" onclick=AppendCharacter("&#02969;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02970" value="&#02970;" onclick=AppendCharacter("&#02970;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02972" value="&#02972;" onclick=AppendCharacter("&#02972;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02974" value="&#02974;" onclick=AppendCharacter("&#02974;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02975" value=" &#02975;" onclick=AppendCharacter("&#02975;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02979" value="&#02979;" onclick=AppendCharacter("&#02979;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02980" value="&#02980;" onclick=AppendCharacter("&#02980;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02984" value="&#02984;" onclick=AppendCharacter("&#02984;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02985" value="&#02985;" onclick=AppendCharacter("&#02985;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02986" value="&#02986;" onclick=AppendCharacter("&#02986;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02990" value="&#02990;" onclick=AppendCharacter("&#02990;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02991" value="&#02991;" onclick=AppendCharacter("&#02991;")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 
  
 document.write('<TABLE>'); 
 document.write('<TR>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02992" value="&#02992;" onclick=AppendCharacter("&#02992;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02993" value="&#02993;" onclick=AppendCharacter("&#02993;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02994" value="&#02994;" onclick=AppendCharacter("&#02994;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02995" value="&#02995;" onclick=AppendCharacter("&#02995;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02996" value="&#02996;" onclick=AppendCharacter("&#02996;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02997" value="&#02997;" onclick=AppendCharacter("&#02997;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02999" value="&#02999;" onclick=AppendCharacter("&#02999;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03000" value="&#03000;" onclick=AppendCharacter("&#03000;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03001" value="&#03001;" onclick=AppendCharacter("&#03001;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03006" value="&#03006;" onclick=AppendCharacter("&#03006;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03007" value="&#03007;" onclick=AppendCharacter("&#03007;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03008" value="&#03008;" onclick=AppendCharacter("&#03008;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03009" value="&#03009;" onclick=AppendCharacter("&#03009;")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 
  
 document.write('<TABLE>'); 
 document.write('<TR>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03010" value="&#03010;" onclick=AppendCharacter("&#03010;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03014" value="&#03014;" onclick=AppendCharacter("&#03014;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03015" value="&#03015;" onclick=AppendCharacter("&#03015;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03016" value="&#03016;" onclick=AppendCharacter("&#03016;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03018" value="&#03018;" onclick=AppendCharacter("&#03018;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03019" value="&#03019;" onclick=AppendCharacter("&#03019;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03020" value="&#03020;" onclick=AppendCharacter("&#03020;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03021" value="&#03021;" onclick=AppendCharacter("&#03021;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="03031" value="&#03031;" onclick=AppendCharacter("&#03031;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" style="font-size: 13; font-weight:bold" name="02947" value="&#02947;" onclick=AppendCharacter("&#02947;")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 
  
 document.write('<TABLE>'); 
 document.write('<TR>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" name="space" value=" Space " onclick=AppendCharacter("&#032;")>'); 
 document.write('</TD>'); 
 document.write('<TD>'); 
 document.write('<INPUT type="button" name="space" value=" Enter " onclick=AppendCharacter("\\n")>'); 
 document.write('</TD>'); 
 document.write('</TR>'); 
 document.write('</TABLE>'); 